### ISSUE TITLE
Does not build with gcc `9.3.0-1`

### ISSUE THREAD

**Issue by gbip** [BynaryCobweb/world#2]
I can't seem to build the project using the latest gcc on manjaro.
```bash
git clone https://github.com/BynaryCobweb/world
cd world
mkdir build
cmake ..
make
```

Results in the following error :
```
/tmp/world/projects/world/math/Perlin.cpp:19:46: error: non-local lambda expression cannot have a capture-default
   19 | Perlin::modifier Perlin::DEFAULT_MODIFIER = [&](double, double, double val) {
      |                                              ^
```

Here is my `gcc --version` :
```
gcc (Arch Linux 9.3.0-1) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

If you intend not to support gcc 9, maybe you should specify which version one should use in the README ?
Nice project by the way :smiley:

**Comment by Bycob** [comment]
Hi!
I was not aware of this problem with gcc 9, I will try to fix the problem! And I will specify the compilers I'm using in the README (currently gcc 7)

**Comment by Bycob** [comment]
The problem should be fixed with f887206, can you try to compile again?

**Comment by gbip** [comment]
It now builds successfully !

**Comment by Bycob** [comment]
Nice! Did you try the demo or one of the test programs?

**Comment by gbip** [comment]
Yep, I also ran the tests, in case of.
